#! /bin/bash
if [ $# -eq 0 ]
then
	echo "Usage: $0 website_root_directory/info"
	exit 1  #error
fi

#Replace html code with that appropriate for the website in use

dir=$1
cat ${dir}/shapes.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Node Shapes<\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"attrs.html"/"attrs"/g  -e s/"a:"/"a"/g -e s/"d:"/"d"/g -e s/"k:"/"k"/g \
-e s/"http:\/\/www.graphviz.org\/doc\/char.html\">"/"\/doc\/char.html\" target=\"_blank\">"/g \
-e s/"A HREF=html"/"A HREF=\/doc\/info\/html"/g \
-e s/"<A HREF=shapes.html"/"<A HREF="/g \
-e s/'SRC='/'SRC=\/doc\/info\/'/g \
> shapes_db


