#! /bin/bash
if [ $# -eq 0 ]
then
	echo "Usage: $0 website_root_directory/info"
	exit 1  #error
fi

#Replace html code with that appropriate for the website in use

dir=$1
cat ${dir}/colors.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Color Names<\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/"attrs.html"/"attrs"/g \
> colors_db


