#! /bin/bash
if [ $# -eq 0 ]
then
	echo "Usage: $0 website_root_directory/info"
	exit 1  #error
fi

#Replace html code with that appropriate for the website in use
dir=$1
cat ${dir}/output.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Output Formats<\/H1><\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/"a:"/"a"/g -e s/"k:"/"k"/g \
| sed -e s/'http:\/\/www.gtk.org\/\">'/'http:\/\/www.gtk.org\/\" target=\"_blank\">'/g \
-e s/'icon_image_file_format)\">'/'icon_image_file_format)\" target=\"_blank\">'/g \
-e s/'devnet\/pdf\/\">'/'devnet\/pdf\/\" target=\"_blank\">'/g \
-e s/'www.adobe.com\/svg\/\">'/'www.adobe.com\/svg\/\" target=\"_blank\">'/g \
-e s/'www.libtiff.org\/\">'/'www.libtiff.org\/\" target=\"_blank\">'/g \
-e s/"TR\/NOTE-VML\">"/"TR\/NOTE-VML\" target=\"blank\">"/g \
-e s/"www.vrml.org\/\">"/"www.vrml.org\/\" target=\"blank\">"/g \
-e s/"wiki\/Xlib\">"/"wiki\/Xlib\" target=\"blank\">"/g \
-e s/"wiki\/Bitmap\">"/"wiki\/Bitmap\" target=\"blank\">"/g \
-e s/"lang.html"/"dot-language"/g  \
-e s/"attrs.html"/"attrs"/g  \
-e s/'SRC=\"'/'SRC=\"\/doc\/info\/'/g  \
> output_db


