#! /bin/bash
if [ $# -eq 0 ]
then
	echo "Usage: $0 website_root_directory/info"
	exit 1  #error
fi

#Replace html code with that appropriate for the website in use

dir=$1
cat ${dir}/attrs.html | sed -e /"DOCTYPE HTML"/,/"BODY BGCOLOR"/d -e /"Node, Edge and Graph Attributes<\/H1>"/d \
-e /"<\/BODY>"/d -e /"<\/HTML>"/d | \
sed -e s/"d:"/"d"/g -e s/"k:"/"k"/g -e s/"a:"/"a"/g \
| sed -e s/'http:\/\/www.graphviz.org\/doc\/info\/lang.html'/'dot-language'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation\/html\/layers\/'/'graphviz-layered-drawing'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation\/html\/shapehowto.html'/'\/Documentation\/html\/shapehowto.html'/g \
-e s/'http:\/\/www.graphviz.org\/doc\/info\/output.html'/'output-formats'/g \
-e s/'http:\/\/www.graphviz.org\/Documentation'/'\/Documentation'/g \
-e s/"output.html"/"output-formats"/g -e s/"attrs.html"/"attrs"/g  -e s/'SRC=\"'/'SRC=\"\/doc\/info\/'/g  \
| sed -e s/"colors.html"/"color-names"/g -e s/"shapes.html"/node-shapes/ \
-e s/"command.html"/"command-line-invocation"/g \
-e s/"arrows.html"/"arrow-shapes"/g \
> attrs_db


