<!-- Do not remove this comment or make any web server edits above this comment -->
<b>Lion</b>: a beta package is available <a href="http://www.graphviz.org/pub/tmp/graphviz-lion-2.29.20110817.pkg">here</a>. No promises but would appreciate feedback either way (gviz-bugs research.att.com). One person told us it works (it was TWEETED).
<p>
<b>Snow Leopard and Leopard</b>: We're having problems with Snow Leopard and Leopard, lately, too. Apparently the universal binaries we build are making don't play nicely on early Intel Macs. So people were swearing at Graphviz on Twitter. As a pro bono effort, It is difficult for us to keep up, both because of the complexity of Graphviz (which depends on a lot of GNU libraries, all the way down to glib2) and OSX itself. (We suspect a recent seemingly minor patch to OSX changed the way one of the OSX frameworks talks to Graphviz for font scaling.) So, big warning here, you may be better off using Homebrew or Macports to install Graphviz by compiling the source (which requires XCode, so allow an afternoon for the process. If you update the package, and you're not happy with the result, there is really no way to undo the installation except from your own backups, or by finding one of the old versions as described below. Anyone that wants to help improve this situation is more than welcome to pitch in.
<p>
<b>General</b>: this package is for general use. It has Graphviz.app and the main command line tools.  It doesn't include gvedit.app (a QT-based graph editor), smyrna (an OpenGL viewer for large graphs), or the pangocairo plugin (you get the quartz plugin instead). If you need any of these, build from the <a href="http://www.graphviz.org/pub/graphviz/CURRENT/graphviz-working.tar.gz">source tarball</a> or <a href="http://www.macports.org/">macports</a> <a href="http://www.macports.org/ports.php?by=name&substr=graphviz">graphviz</a>. If you can work on fixing the build and packaging problems with these tools, send mail to gviz-bugs on research.att.com. (Note: smyrna crashes Xquartz 2.6.1 on some systems; update to <a href="http://xquartz.macosforge.org/trac/wiki/Releases">2.6.2</a>.)
<p>For older versions of Graphviz for Tiger, Leopard or Snow Leopard, look <a href="http://www.graphviz.org/pub/graphviz/stable/macos/">here</a>.

<!-- Do not remove this comment or make any web server edits below this comment -->
<!-- cut2 -->
}

puts $fout "<table frame=\"void\" rules=\"groups\" border=\"1\" width=\"100%\">"
for {set i 0} {$i <= [llength $releases] / 2} {incr i} {
    puts $fout "<colgroup><col></colgroup>"
}

foreach {package platforms} $packages_platforms {
    puts $fout "<!--- The file is automatically generated by macos_current.tcl --->"
#    puts $fout "The current <b>stable</b> release <b>does not install cleanly"
#    puts $fout "on OSX 10.6 (Snow Leopard)</b>. We know this! No need to file"
#    puts $fout "any bug reports. The current <b>development</b> release installs"
#    puts $fout "cleanly on OSX 10.6, but it can crash if the graph file"
#    puts $fout "is changed in the background while the graph is being viewed."
#    puts $fout "Other than these known errors, please report bugs in the usual way"
#    puts $fout "(website or mail form to gviz-bugs). If you're impatient,"
#    puts $fout "you can always try installing Graphviz via Macports.<p>"
    puts $fout ""
    puts $fout "<tbody>"
    puts $fout "<tr>"
    puts $fout "<th align=\"left\"><font size=\"+1\">$package</font></th>"
    foreach {releasename releasedir} $releases {
    	puts $fout "<th><font size=\"-1\">$releasename</font></th>"
    }
    puts $fout "</tr>"
    puts $fout "</tbody>"
    foreach {platform directory types comment} $platform_directory_type_comments {
	if {[lsearch $platforms $platform] == -1} continue
        set pkg $package
        puts $fout "<tbody>"
        puts $fout "<tr><th align=\"right\"><font size=\"-1\">$platform</font></th>"
        foreach {releasename releasedir} $releases {
            puts $fout "<td align=\"left\" nowrap><font size=\"-1\">"
            foreach type $types {
                puts_latest $fout $docroot $releasedir/$directory $pkg $package_exclude $type
            }
            puts $fout "</font></td>"
        }
        puts $fout "</tr>"
        puts $fout "</tbody>"
    }

    puts $fout "<tbody>"
    puts $fout "<tr><td colspan=\"[expr {1 + ([llength $releases] / 2)}]\">&nbsp;</td></tr>"
    puts $fout "</tbody>"
}

puts $fout "</table>"

close $fout
